// Code generated by protoc-gen-go. DO NOT EDIT.
// source: beyond.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//SortedMap messages.
type SM struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM) Reset()         { *m = SM{} }
func (m *SM) String() string { return proto.CompactTextString(m) }
func (*SM) ProtoMessage()    {}
func (*SM) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0}
}

func (m *SM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM.Unmarshal(m, b)
}
func (m *SM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM.Marshal(b, m, deterministic)
}
func (m *SM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM.Merge(m, src)
}
func (m *SM) XXX_Size() int {
	return xxx_messageInfo_SM.Size(m)
}
func (m *SM) XXX_DiscardUnknown() {
	xxx_messageInfo_SM.DiscardUnknown(m)
}

var xxx_messageInfo_SM proto.InternalMessageInfo

// messages used for both request and response.
type SM_Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM_Empty) Reset()         { *m = SM_Empty{} }
func (m *SM_Empty) String() string { return proto.CompactTextString(m) }
func (*SM_Empty) ProtoMessage()    {}
func (*SM_Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0, 0}
}

func (m *SM_Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM_Empty.Unmarshal(m, b)
}
func (m *SM_Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM_Empty.Marshal(b, m, deterministic)
}
func (m *SM_Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM_Empty.Merge(m, src)
}
func (m *SM_Empty) XXX_Size() int {
	return xxx_messageInfo_SM_Empty.Size(m)
}
func (m *SM_Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_SM_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_SM_Empty proto.InternalMessageInfo

// messages used for request only.
type SM_Name struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM_Name) Reset()         { *m = SM_Name{} }
func (m *SM_Name) String() string { return proto.CompactTextString(m) }
func (*SM_Name) ProtoMessage()    {}
func (*SM_Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0, 1}
}

func (m *SM_Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM_Name.Unmarshal(m, b)
}
func (m *SM_Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM_Name.Marshal(b, m, deterministic)
}
func (m *SM_Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM_Name.Merge(m, src)
}
func (m *SM_Name) XXX_Size() int {
	return xxx_messageInfo_SM_Name.Size(m)
}
func (m *SM_Name) XXX_DiscardUnknown() {
	xxx_messageInfo_SM_Name.DiscardUnknown(m)
}

var xxx_messageInfo_SM_Name proto.InternalMessageInfo

func (m *SM_Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SM_NameKey struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM_NameKey) Reset()         { *m = SM_NameKey{} }
func (m *SM_NameKey) String() string { return proto.CompactTextString(m) }
func (*SM_NameKey) ProtoMessage()    {}
func (*SM_NameKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0, 2}
}

func (m *SM_NameKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM_NameKey.Unmarshal(m, b)
}
func (m *SM_NameKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM_NameKey.Marshal(b, m, deterministic)
}
func (m *SM_NameKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM_NameKey.Merge(m, src)
}
func (m *SM_NameKey) XXX_Size() int {
	return xxx_messageInfo_SM_NameKey.Size(m)
}
func (m *SM_NameKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SM_NameKey.DiscardUnknown(m)
}

var xxx_messageInfo_SM_NameKey proto.InternalMessageInfo

func (m *SM_NameKey) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SM_NameKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type SM_NameKeyValueReplace struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Replace              bool     `protobuf:"varint,4,opt,name=replace,proto3" json:"replace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM_NameKeyValueReplace) Reset()         { *m = SM_NameKeyValueReplace{} }
func (m *SM_NameKeyValueReplace) String() string { return proto.CompactTextString(m) }
func (*SM_NameKeyValueReplace) ProtoMessage()    {}
func (*SM_NameKeyValueReplace) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0, 3}
}

func (m *SM_NameKeyValueReplace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM_NameKeyValueReplace.Unmarshal(m, b)
}
func (m *SM_NameKeyValueReplace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM_NameKeyValueReplace.Marshal(b, m, deterministic)
}
func (m *SM_NameKeyValueReplace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM_NameKeyValueReplace.Merge(m, src)
}
func (m *SM_NameKeyValueReplace) XXX_Size() int {
	return xxx_messageInfo_SM_NameKeyValueReplace.Size(m)
}
func (m *SM_NameKeyValueReplace) XXX_DiscardUnknown() {
	xxx_messageInfo_SM_NameKeyValueReplace.DiscardUnknown(m)
}

var xxx_messageInfo_SM_NameKeyValueReplace proto.InternalMessageInfo

func (m *SM_NameKeyValueReplace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SM_NameKeyValueReplace) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SM_NameKeyValueReplace) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SM_NameKeyValueReplace) GetReplace() bool {
	if m != nil {
		return m.Replace
	}
	return false
}

type SM_NameKeyReverseOffsetLimit struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Reverse              bool     `protobuf:"varint,3,opt,name=reverse,proto3" json:"reverse,omitempty"`
	Offset               uint64   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint64   `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM_NameKeyReverseOffsetLimit) Reset()         { *m = SM_NameKeyReverseOffsetLimit{} }
func (m *SM_NameKeyReverseOffsetLimit) String() string { return proto.CompactTextString(m) }
func (*SM_NameKeyReverseOffsetLimit) ProtoMessage()    {}
func (*SM_NameKeyReverseOffsetLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0, 4}
}

func (m *SM_NameKeyReverseOffsetLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM_NameKeyReverseOffsetLimit.Unmarshal(m, b)
}
func (m *SM_NameKeyReverseOffsetLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM_NameKeyReverseOffsetLimit.Marshal(b, m, deterministic)
}
func (m *SM_NameKeyReverseOffsetLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM_NameKeyReverseOffsetLimit.Merge(m, src)
}
func (m *SM_NameKeyReverseOffsetLimit) XXX_Size() int {
	return xxx_messageInfo_SM_NameKeyReverseOffsetLimit.Size(m)
}
func (m *SM_NameKeyReverseOffsetLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_SM_NameKeyReverseOffsetLimit.DiscardUnknown(m)
}

var xxx_messageInfo_SM_NameKeyReverseOffsetLimit proto.InternalMessageInfo

func (m *SM_NameKeyReverseOffsetLimit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SM_NameKeyReverseOffsetLimit) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SM_NameKeyReverseOffsetLimit) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *SM_NameKeyReverseOffsetLimit) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SM_NameKeyReverseOffsetLimit) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type SM_OP struct {
	Op                   []byte   `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM_OP) Reset()         { *m = SM_OP{} }
func (m *SM_OP) String() string { return proto.CompactTextString(m) }
func (*SM_OP) ProtoMessage()    {}
func (*SM_OP) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0, 5}
}

func (m *SM_OP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM_OP.Unmarshal(m, b)
}
func (m *SM_OP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM_OP.Marshal(b, m, deterministic)
}
func (m *SM_OP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM_OP.Merge(m, src)
}
func (m *SM_OP) XXX_Size() int {
	return xxx_messageInfo_SM_OP.Size(m)
}
func (m *SM_OP) XXX_DiscardUnknown() {
	xxx_messageInfo_SM_OP.DiscardUnknown(m)
}

var xxx_messageInfo_SM_OP proto.InternalMessageInfo

func (m *SM_OP) GetOp() []byte {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *SM_OP) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SM_OP) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SM_NameTransaction struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Op                   []*SM_OP `protobuf:"bytes,2,rep,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM_NameTransaction) Reset()         { *m = SM_NameTransaction{} }
func (m *SM_NameTransaction) String() string { return proto.CompactTextString(m) }
func (*SM_NameTransaction) ProtoMessage()    {}
func (*SM_NameTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0, 6}
}

func (m *SM_NameTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM_NameTransaction.Unmarshal(m, b)
}
func (m *SM_NameTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM_NameTransaction.Marshal(b, m, deterministic)
}
func (m *SM_NameTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM_NameTransaction.Merge(m, src)
}
func (m *SM_NameTransaction) XXX_Size() int {
	return xxx_messageInfo_SM_NameTransaction.Size(m)
}
func (m *SM_NameTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_SM_NameTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_SM_NameTransaction proto.InternalMessageInfo

func (m *SM_NameTransaction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SM_NameTransaction) GetOp() []*SM_OP {
	if m != nil {
		return m.Op
	}
	return nil
}

type SM_NameOPKeyValue struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Op                   []byte   `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Key                  []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM_NameOPKeyValue) Reset()         { *m = SM_NameOPKeyValue{} }
func (m *SM_NameOPKeyValue) String() string { return proto.CompactTextString(m) }
func (*SM_NameOPKeyValue) ProtoMessage()    {}
func (*SM_NameOPKeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0, 7}
}

func (m *SM_NameOPKeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM_NameOPKeyValue.Unmarshal(m, b)
}
func (m *SM_NameOPKeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM_NameOPKeyValue.Marshal(b, m, deterministic)
}
func (m *SM_NameOPKeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM_NameOPKeyValue.Merge(m, src)
}
func (m *SM_NameOPKeyValue) XXX_Size() int {
	return xxx_messageInfo_SM_NameOPKeyValue.Size(m)
}
func (m *SM_NameOPKeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SM_NameOPKeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_SM_NameOPKeyValue proto.InternalMessageInfo

func (m *SM_NameOPKeyValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SM_NameOPKeyValue) GetOp() []byte {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *SM_NameOPKeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SM_NameOPKeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// messages used for response only.
type SM_Names struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM_Names) Reset()         { *m = SM_Names{} }
func (m *SM_Names) String() string { return proto.CompactTextString(m) }
func (*SM_Names) ProtoMessage()    {}
func (*SM_Names) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0, 8}
}

func (m *SM_Names) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM_Names.Unmarshal(m, b)
}
func (m *SM_Names) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM_Names.Marshal(b, m, deterministic)
}
func (m *SM_Names) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM_Names.Merge(m, src)
}
func (m *SM_Names) XXX_Size() int {
	return xxx_messageInfo_SM_Names.Size(m)
}
func (m *SM_Names) XXX_DiscardUnknown() {
	xxx_messageInfo_SM_Names.DiscardUnknown(m)
}

var xxx_messageInfo_SM_Names proto.InternalMessageInfo

func (m *SM_Names) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type SM_Length struct {
	Length               uint64   `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM_Length) Reset()         { *m = SM_Length{} }
func (m *SM_Length) String() string { return proto.CompactTextString(m) }
func (*SM_Length) ProtoMessage()    {}
func (*SM_Length) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0, 9}
}

func (m *SM_Length) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM_Length.Unmarshal(m, b)
}
func (m *SM_Length) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM_Length.Marshal(b, m, deterministic)
}
func (m *SM_Length) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM_Length.Merge(m, src)
}
func (m *SM_Length) XXX_Size() int {
	return xxx_messageInfo_SM_Length.Size(m)
}
func (m *SM_Length) XXX_DiscardUnknown() {
	xxx_messageInfo_SM_Length.DiscardUnknown(m)
}

var xxx_messageInfo_SM_Length proto.InternalMessageInfo

func (m *SM_Length) GetLength() uint64 {
	if m != nil {
		return m.Length
	}
	return 0
}

type SM_Value struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM_Value) Reset()         { *m = SM_Value{} }
func (m *SM_Value) String() string { return proto.CompactTextString(m) }
func (*SM_Value) ProtoMessage()    {}
func (*SM_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0, 10}
}

func (m *SM_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM_Value.Unmarshal(m, b)
}
func (m *SM_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM_Value.Marshal(b, m, deterministic)
}
func (m *SM_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM_Value.Merge(m, src)
}
func (m *SM_Value) XXX_Size() int {
	return xxx_messageInfo_SM_Value.Size(m)
}
func (m *SM_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_SM_Value.DiscardUnknown(m)
}

var xxx_messageInfo_SM_Value proto.InternalMessageInfo

func (m *SM_Value) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SM_KeyValue struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SM_KeyValue) Reset()         { *m = SM_KeyValue{} }
func (m *SM_KeyValue) String() string { return proto.CompactTextString(m) }
func (*SM_KeyValue) ProtoMessage()    {}
func (*SM_KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b2f43be8528e93, []int{0, 11}
}

func (m *SM_KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SM_KeyValue.Unmarshal(m, b)
}
func (m *SM_KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SM_KeyValue.Marshal(b, m, deterministic)
}
func (m *SM_KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SM_KeyValue.Merge(m, src)
}
func (m *SM_KeyValue) XXX_Size() int {
	return xxx_messageInfo_SM_KeyValue.Size(m)
}
func (m *SM_KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SM_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_SM_KeyValue proto.InternalMessageInfo

func (m *SM_KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SM_KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*SM)(nil), "grpc.SM")
	proto.RegisterType((*SM_Empty)(nil), "grpc.SM.Empty")
	proto.RegisterType((*SM_Name)(nil), "grpc.SM.Name")
	proto.RegisterType((*SM_NameKey)(nil), "grpc.SM.NameKey")
	proto.RegisterType((*SM_NameKeyValueReplace)(nil), "grpc.SM.NameKeyValueReplace")
	proto.RegisterType((*SM_NameKeyReverseOffsetLimit)(nil), "grpc.SM.NameKeyReverseOffsetLimit")
	proto.RegisterType((*SM_OP)(nil), "grpc.SM.OP")
	proto.RegisterType((*SM_NameTransaction)(nil), "grpc.SM.NameTransaction")
	proto.RegisterType((*SM_NameOPKeyValue)(nil), "grpc.SM.NameOPKeyValue")
	proto.RegisterType((*SM_Names)(nil), "grpc.SM.Names")
	proto.RegisterType((*SM_Length)(nil), "grpc.SM.Length")
	proto.RegisterType((*SM_Value)(nil), "grpc.SM.Value")
	proto.RegisterType((*SM_KeyValue)(nil), "grpc.SM.KeyValue")
}

func init() { proto.RegisterFile("beyond.proto", fileDescriptor_01b2f43be8528e93) }

var fileDescriptor_01b2f43be8528e93 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x4e,
	0x10, 0x8f, 0x3f, 0x93, 0x4e, 0xd3, 0x34, 0xff, 0xfd, 0x23, 0x30, 0x0b, 0x48, 0x96, 0x4f, 0x06,
	0xa4, 0x80, 0xc2, 0x01, 0x21, 0x38, 0x15, 0x38, 0x20, 0x62, 0x62, 0xd9, 0x88, 0x13, 0x17, 0x37,
	0x4c, 0x4b, 0xd4, 0xf8, 0x43, 0xeb, 0x6d, 0xa4, 0x3c, 0x02, 0x4f, 0xc6, 0xa3, 0xf0, 0x1a, 0x68,
	0xc7, 0x8e, 0x71, 0x5c, 0x1f, 0x72, 0xdb, 0xdf, 0xce, 0xfc, 0x3e, 0x76, 0x32, 0x0e, 0x8c, 0x2f,
	0x71, 0x97, 0x67, 0x3f, 0x66, 0x85, 0xc8, 0x65, 0xce, 0xcc, 0x6b, 0x51, 0xac, 0xbc, 0xdf, 0x16,
	0xe8, 0x71, 0xc0, 0x87, 0x60, 0x7d, 0x4c, 0x0b, 0xb9, 0xe3, 0x1c, 0xcc, 0x2f, 0x49, 0x8a, 0x8c,
	0x81, 0x99, 0x25, 0x29, 0x3a, 0x9a, 0xab, 0xf9, 0x27, 0x11, 0x9d, 0xf9, 0x0b, 0x18, 0xaa, 0xda,
	0x67, 0xdc, 0xf5, 0x95, 0xd9, 0x14, 0x8c, 0x1b, 0xdc, 0x39, 0xba, 0xab, 0xf9, 0xe3, 0x48, 0x1d,
	0xf9, 0x0d, 0xfc, 0x5f, 0x13, 0xbe, 0x25, 0x9b, 0x5b, 0x8c, 0xb0, 0xd8, 0x24, 0x2b, 0x3c, 0x8e,
	0xcc, 0xee, 0x81, 0xb5, 0x55, 0x2c, 0xc7, 0xa0, 0xbb, 0x0a, 0x30, 0x07, 0x86, 0xa2, 0x92, 0x71,
	0x4c, 0x57, 0xf3, 0x47, 0xd1, 0x1e, 0xf2, 0x5f, 0x1a, 0x3c, 0xac, 0xdd, 0x22, 0xdc, 0xa2, 0x28,
	0x71, 0x79, 0x75, 0x55, 0xa2, 0x5c, 0xac, 0xd3, 0xb5, 0x3c, 0xd2, 0x93, 0xd4, 0x89, 0x4b, 0xae,
	0xa4, 0x4e, 0x90, 0xdd, 0x07, 0x3b, 0x27, 0x39, 0xb2, 0x35, 0xa3, 0x1a, 0xa9, 0x94, 0x1b, 0x65,
	0xe0, 0x58, 0x74, 0x5d, 0x01, 0xfe, 0x0e, 0xf4, 0x65, 0xc8, 0x26, 0xa0, 0xe7, 0x05, 0x39, 0x8e,
	0x23, 0x3d, 0x2f, 0x8e, 0x7d, 0x23, 0xbf, 0x80, 0x73, 0xf5, 0x90, 0xaf, 0x22, 0xc9, 0xca, 0x64,
	0x25, 0xd7, 0x79, 0xd6, 0x1b, 0xff, 0x11, 0xc9, 0xeb, 0xae, 0xe1, 0x9f, 0xce, 0x4f, 0x67, 0xea,
	0xd7, 0x9c, 0xc5, 0xc1, 0x6c, 0x19, 0x2a, 0x2f, 0xfe, 0x1d, 0x26, 0x4a, 0x63, 0x19, 0xee, 0x87,
	0xdf, 0x2b, 0x31, 0xa9, 0x25, 0x3a, 0x09, 0x8d, 0x9e, 0x84, 0x66, 0x3b, 0xe1, 0x13, 0xb0, 0x94,
	0x7a, 0xa9, 0xca, 0x4a, 0xa8, 0x74, 0x34, 0xd7, 0xf0, 0x4f, 0xa2, 0x0a, 0x70, 0x17, 0xec, 0x05,
	0x66, 0xd7, 0xf2, 0xa7, 0x1a, 0xdb, 0x86, 0x4e, 0x64, 0x6b, 0x46, 0x35, 0x52, 0x02, 0x55, 0xaa,
	0x46, 0x5f, 0x6b, 0xeb, 0xcf, 0x61, 0xd4, 0xe4, 0xae, 0x33, 0x69, 0x3d, 0x99, 0xf4, 0x16, 0x67,
	0xfe, 0xc7, 0x00, 0xfb, 0x82, 0x16, 0x9c, 0x3d, 0x87, 0xd1, 0x7b, 0x81, 0x89, 0xc4, 0x38, 0x60,
	0x67, 0xcd, 0x64, 0x54, 0x62, 0x3e, 0x69, 0x20, 0xed, 0xbb, 0x37, 0x60, 0x4f, 0xc1, 0xfe, 0x20,
	0xf2, 0xe2, 0x98, 0xd6, 0x67, 0x60, 0x2f, 0xd6, 0xa5, 0x8c, 0x03, 0xd6, 0xa9, 0xb5, 0x7a, 0x69,
	0x2e, 0x24, 0x6b, 0xc5, 0xc1, 0x02, 0xb3, 0xae, 0xea, 0x79, 0x03, 0xab, 0x11, 0x79, 0x03, 0xf6,
	0x5a, 0xb5, 0x86, 0xb7, 0x92, 0x3d, 0x3e, 0x68, 0xed, 0x7c, 0x36, 0x2d, 0x0f, 0xba, 0xf6, 0x06,
	0x6c, 0x06, 0xa3, 0x38, 0x88, 0x30, 0xcd, 0xb7, 0xc8, 0xa6, 0x5d, 0x6e, 0x4f, 0xff, 0x5b, 0x38,
	0x8b, 0x83, 0xf6, 0x5a, 0x39, 0x07, 0xa4, 0x56, 0xa5, 0xe7, 0xf1, 0x6f, 0x00, 0xe2, 0x60, 0x19,
	0xc6, 0x52, 0x60, 0x92, 0xb2, 0x07, 0x07, 0xcc, 0x7f, 0x6b, 0x76, 0x97, 0xe8, 0x6b, 0x2c, 0x80,
	0x69, 0x1c, 0x7c, 0x92, 0x28, 0x12, 0x99, 0x8b, 0x5a, 0xc0, 0xeb, 0xe6, 0xbd, 0xfb, 0xd1, 0xf2,
	0xff, 0x9a, 0x9e, 0xbd, 0xbc, 0x37, 0x78, 0xa9, 0x5d, 0xda, 0xf4, 0x07, 0xf6, 0xea, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe3, 0xed, 0x78, 0x59, 0xd0, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BeyondClient is the client API for Beyond service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BeyondClient interface {
	// [management rpc]
	// create sorted map with given name.
	CreateSM(ctx context.Context, in *SM_Name, opts ...grpc.CallOption) (*SM_Empty, error)
	// drop sorted map with given name.
	DropSM(ctx context.Context, in *SM_Name, opts ...grpc.CallOption) (*SM_Empty, error)
	// list all sorted map.
	ListSM(ctx context.Context, in *SM_Empty, opts ...grpc.CallOption) (*SM_Names, error)
	// [operation rpc]
	// get length of given sorted map.
	SMLen(ctx context.Context, in *SM_Name, opts ...grpc.CallOption) (*SM_Length, error)
	// put key-value into given sorted map.
	SMPut(ctx context.Context, in *SM_NameKeyValueReplace, opts ...grpc.CallOption) (*SM_Value, error)
	// remove key from given sorted map.
	SMRemove(ctx context.Context, in *SM_NameKey, opts ...grpc.CallOption) (*SM_Value, error)
	SMTransaction(ctx context.Context, in *SM_NameTransaction, opts ...grpc.CallOption) (*SM_Empty, error)
	// [streaming rpc]
	SMOPStream(ctx context.Context, opts ...grpc.CallOption) (Beyond_SMOPStreamClient, error)
	SMIteratorStream(ctx context.Context, in *SM_NameKeyReverseOffsetLimit, opts ...grpc.CallOption) (Beyond_SMIteratorStreamClient, error)
}

type beyondClient struct {
	cc *grpc.ClientConn
}

func NewBeyondClient(cc *grpc.ClientConn) BeyondClient {
	return &beyondClient{cc}
}

func (c *beyondClient) CreateSM(ctx context.Context, in *SM_Name, opts ...grpc.CallOption) (*SM_Empty, error) {
	out := new(SM_Empty)
	err := c.cc.Invoke(ctx, "/grpc.Beyond/CreateSM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beyondClient) DropSM(ctx context.Context, in *SM_Name, opts ...grpc.CallOption) (*SM_Empty, error) {
	out := new(SM_Empty)
	err := c.cc.Invoke(ctx, "/grpc.Beyond/DropSM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beyondClient) ListSM(ctx context.Context, in *SM_Empty, opts ...grpc.CallOption) (*SM_Names, error) {
	out := new(SM_Names)
	err := c.cc.Invoke(ctx, "/grpc.Beyond/ListSM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beyondClient) SMLen(ctx context.Context, in *SM_Name, opts ...grpc.CallOption) (*SM_Length, error) {
	out := new(SM_Length)
	err := c.cc.Invoke(ctx, "/grpc.Beyond/SMLen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beyondClient) SMPut(ctx context.Context, in *SM_NameKeyValueReplace, opts ...grpc.CallOption) (*SM_Value, error) {
	out := new(SM_Value)
	err := c.cc.Invoke(ctx, "/grpc.Beyond/SMPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beyondClient) SMRemove(ctx context.Context, in *SM_NameKey, opts ...grpc.CallOption) (*SM_Value, error) {
	out := new(SM_Value)
	err := c.cc.Invoke(ctx, "/grpc.Beyond/SMRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beyondClient) SMTransaction(ctx context.Context, in *SM_NameTransaction, opts ...grpc.CallOption) (*SM_Empty, error) {
	out := new(SM_Empty)
	err := c.cc.Invoke(ctx, "/grpc.Beyond/SMTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beyondClient) SMOPStream(ctx context.Context, opts ...grpc.CallOption) (Beyond_SMOPStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Beyond_serviceDesc.Streams[0], "/grpc.Beyond/SMOPStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &beyondSMOPStreamClient{stream}
	return x, nil
}

type Beyond_SMOPStreamClient interface {
	Send(*SM_NameOPKeyValue) error
	CloseAndRecv() (*SM_Empty, error)
	grpc.ClientStream
}

type beyondSMOPStreamClient struct {
	grpc.ClientStream
}

func (x *beyondSMOPStreamClient) Send(m *SM_NameOPKeyValue) error {
	return x.ClientStream.SendMsg(m)
}

func (x *beyondSMOPStreamClient) CloseAndRecv() (*SM_Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SM_Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *beyondClient) SMIteratorStream(ctx context.Context, in *SM_NameKeyReverseOffsetLimit, opts ...grpc.CallOption) (Beyond_SMIteratorStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Beyond_serviceDesc.Streams[1], "/grpc.Beyond/SMIteratorStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &beyondSMIteratorStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Beyond_SMIteratorStreamClient interface {
	Recv() (*SM_KeyValue, error)
	grpc.ClientStream
}

type beyondSMIteratorStreamClient struct {
	grpc.ClientStream
}

func (x *beyondSMIteratorStreamClient) Recv() (*SM_KeyValue, error) {
	m := new(SM_KeyValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BeyondServer is the server API for Beyond service.
type BeyondServer interface {
	// [management rpc]
	// create sorted map with given name.
	CreateSM(context.Context, *SM_Name) (*SM_Empty, error)
	// drop sorted map with given name.
	DropSM(context.Context, *SM_Name) (*SM_Empty, error)
	// list all sorted map.
	ListSM(context.Context, *SM_Empty) (*SM_Names, error)
	// [operation rpc]
	// get length of given sorted map.
	SMLen(context.Context, *SM_Name) (*SM_Length, error)
	// put key-value into given sorted map.
	SMPut(context.Context, *SM_NameKeyValueReplace) (*SM_Value, error)
	// remove key from given sorted map.
	SMRemove(context.Context, *SM_NameKey) (*SM_Value, error)
	SMTransaction(context.Context, *SM_NameTransaction) (*SM_Empty, error)
	// [streaming rpc]
	SMOPStream(Beyond_SMOPStreamServer) error
	SMIteratorStream(*SM_NameKeyReverseOffsetLimit, Beyond_SMIteratorStreamServer) error
}

func RegisterBeyondServer(s *grpc.Server, srv BeyondServer) {
	s.RegisterService(&_Beyond_serviceDesc, srv)
}

func _Beyond_CreateSM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SM_Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeyondServer).CreateSM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Beyond/CreateSM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeyondServer).CreateSM(ctx, req.(*SM_Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _Beyond_DropSM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SM_Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeyondServer).DropSM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Beyond/DropSM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeyondServer).DropSM(ctx, req.(*SM_Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _Beyond_ListSM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SM_Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeyondServer).ListSM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Beyond/ListSM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeyondServer).ListSM(ctx, req.(*SM_Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Beyond_SMLen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SM_Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeyondServer).SMLen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Beyond/SMLen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeyondServer).SMLen(ctx, req.(*SM_Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _Beyond_SMPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SM_NameKeyValueReplace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeyondServer).SMPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Beyond/SMPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeyondServer).SMPut(ctx, req.(*SM_NameKeyValueReplace))
	}
	return interceptor(ctx, in, info, handler)
}

func _Beyond_SMRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SM_NameKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeyondServer).SMRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Beyond/SMRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeyondServer).SMRemove(ctx, req.(*SM_NameKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Beyond_SMTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SM_NameTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeyondServer).SMTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Beyond/SMTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeyondServer).SMTransaction(ctx, req.(*SM_NameTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Beyond_SMOPStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BeyondServer).SMOPStream(&beyondSMOPStreamServer{stream})
}

type Beyond_SMOPStreamServer interface {
	SendAndClose(*SM_Empty) error
	Recv() (*SM_NameOPKeyValue, error)
	grpc.ServerStream
}

type beyondSMOPStreamServer struct {
	grpc.ServerStream
}

func (x *beyondSMOPStreamServer) SendAndClose(m *SM_Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *beyondSMOPStreamServer) Recv() (*SM_NameOPKeyValue, error) {
	m := new(SM_NameOPKeyValue)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Beyond_SMIteratorStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SM_NameKeyReverseOffsetLimit)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BeyondServer).SMIteratorStream(m, &beyondSMIteratorStreamServer{stream})
}

type Beyond_SMIteratorStreamServer interface {
	Send(*SM_KeyValue) error
	grpc.ServerStream
}

type beyondSMIteratorStreamServer struct {
	grpc.ServerStream
}

func (x *beyondSMIteratorStreamServer) Send(m *SM_KeyValue) error {
	return x.ServerStream.SendMsg(m)
}

var _Beyond_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Beyond",
	HandlerType: (*BeyondServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSM",
			Handler:    _Beyond_CreateSM_Handler,
		},
		{
			MethodName: "DropSM",
			Handler:    _Beyond_DropSM_Handler,
		},
		{
			MethodName: "ListSM",
			Handler:    _Beyond_ListSM_Handler,
		},
		{
			MethodName: "SMLen",
			Handler:    _Beyond_SMLen_Handler,
		},
		{
			MethodName: "SMPut",
			Handler:    _Beyond_SMPut_Handler,
		},
		{
			MethodName: "SMRemove",
			Handler:    _Beyond_SMRemove_Handler,
		},
		{
			MethodName: "SMTransaction",
			Handler:    _Beyond_SMTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SMOPStream",
			Handler:       _Beyond_SMOPStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SMIteratorStream",
			Handler:       _Beyond_SMIteratorStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "beyond.proto",
}
